defaults: &defaults
  name: rinha-db
  user: rinha-db
  password: rinha-db
  host: rinha-db
  port: 5432

debug:
  <<: *defaults

test:
  <<: *defaults
  name: test-rinha-db

release:
  <<: *defaults
  name: prod-rinha-db
